[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "brainseg-ai"
version = "1.6.1"
description = "Brain abnormality segmentation application"
readme = "README.md"
authors = [{ name = "Md. Rasel Mandol" }]
requires-python = ">=3.10"
dependencies = [
    "torch",
    "torchvision",
    "segmentation-models-pytorch",
    "matplotlib",
    "gradio",
    "opencv-python",
    "numpy",
    "scipy",
    "psutil",
    "PyQt6",
]

[project.scripts]
brainseg = "brainseg.main:main"

[tool.setuptools.packages.find]
include = ["brainseg", "brainseg.*"]

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
brainseg = [
    "assets/*.png",
    "assets/*.ico",
]
